/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ReTweetService } from "../reTweet.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ReTweetCreateInput } from "./ReTweetCreateInput";
import { ReTweet } from "./ReTweet";
import { ReTweetFindManyArgs } from "./ReTweetFindManyArgs";
import { ReTweetWhereUniqueInput } from "./ReTweetWhereUniqueInput";
import { ReTweetUpdateInput } from "./ReTweetUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ReTweetControllerBase {
  constructor(
    protected readonly service: ReTweetService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ReTweet })
  @nestAccessControl.UseRoles({
    resource: "ReTweet",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createReTweet(
    @common.Body() data: ReTweetCreateInput
  ): Promise<ReTweet> {
    return await this.service.createReTweet({
      data: data,
      select: {
        createdAt: true,
        id: true,
        originalTweet: true,
        retweeter: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ReTweet] })
  @ApiNestedQuery(ReTweetFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ReTweet",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async reTweets(@common.Req() request: Request): Promise<ReTweet[]> {
    const args = plainToClass(ReTweetFindManyArgs, request.query);
    return this.service.reTweets({
      ...args,
      select: {
        createdAt: true,
        id: true,
        originalTweet: true,
        retweeter: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ReTweet })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ReTweet",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async reTweet(
    @common.Param() params: ReTweetWhereUniqueInput
  ): Promise<ReTweet | null> {
    const result = await this.service.reTweet({
      where: params,
      select: {
        createdAt: true,
        id: true,
        originalTweet: true,
        retweeter: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ReTweet })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ReTweet",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateReTweet(
    @common.Param() params: ReTweetWhereUniqueInput,
    @common.Body() data: ReTweetUpdateInput
  ): Promise<ReTweet | null> {
    try {
      return await this.service.updateReTweet({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          originalTweet: true,
          retweeter: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ReTweet })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ReTweet",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteReTweet(
    @common.Param() params: ReTweetWhereUniqueInput
  ): Promise<ReTweet | null> {
    try {
      return await this.service.deleteReTweet({
        where: params,
        select: {
          createdAt: true,
          id: true,
          originalTweet: true,
          retweeter: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
